type Query {
  manufacturers: [Manufacturer!]
  manufacturer: Manufacturer!
  locomotiveModels: [LocomotiveModel!]
  locomotiveModel: LocomotiveModel!
  owners: [Owner!]
  owner: Owner!
  locomotives: [Locomotive!]
  locomotive: Locomotive!
  tags: [Tag!]
  tag: Tag!
  pictures: [Picture!]
  picture: Picture!
  documentations: [Documentation!]
  documentation: Documentation!
  associations: [Owner!]
  association(id: ID!): Owner!
}

type Mutation {
  createManufacturer(
    token: String!
    name: String!
    shortName: String!
    country: String!
    creationDate: String!
    works: Boolean!
    dateOfLiquidation: String
    heroImage: ID
  ): Manufacturer!
  updateManufacturer(
    token: String!
    id: ID!
    name: String!
    shortName: String!
    country: String!
    creationDate: String!
    works: Boolean!
    dateOfLiquidation: String
    heroImage: ID
  ): Manufacturer!
  deleteManufacturer(token: String!, id: ID!): Manufacturer!
  createLocomotiveModel(
    token: String!
    factoryType: [String!]
    manufacturer: [ID!]
    intendentUse: String!
    tractionType: String!
    specTable: String!
    series: [String!]
    heroImage: ID
  ): LocomotiveModel!
  updateLocomotiveModel(
    token: String!
    id: ID!
    factoryType: [String!]
    manufacturer: [ID!]
    intendentUse: String!
    tractionType: String!
    specTable: String!
    series: [String!]
    heroImage: ID
  ): LocomotiveModel!
  deleteLocomotiveModel(token: String!, id: ID!): LocomotiveModel!
  createOwner(
    token: String!
    name: String!
    isAssociation: Boolean!
    adress: String!
    geopoint: String!
    website: String
    heroImage: ID 
  ): Owner!
  updateOwner(
    token: String!
    id: ID!
    name: String!
    isAssociation: Boolean!
    adress: String!
    geopoint: String!
    website: String
    heroImage: ID
  ): Owner!
  deleteOwner(token: String!, id: ID!): Owner!
  createLocomotive(
    token: String!
    Float: String!
    model: ID!
    owner: ID!
    manufacturer: ID!
    state: String!
    assignments: String
    repairHistory: String
    countryOfOperation: String!
    heroImage: ID
  ): Locomotive!
  updateLocomotive(
    token: String!
    id: ID!
    Float: String!
    model: ID!
    owner: ID!
    manufacturer: ID!
    state: String!
    assignments: String
    repairHistory: String
    countryOfOperation: String!
    heroImage: ID
  ): Locomotive!
  deleteLocomotive(token: String!, id: ID!): Locomotive!
  createTag(token: String!, name: String!): Tag!
  updateTag(token: String!, id: ID!, name: String!): Tag!
  deleteTag(token: String!, id: ID!): Tag!
  createPicture(
    token: String!
    units: [ID!]
    models: [ID!]
    description: String!
    date: String!
    tags: [ID!]
  ): Picture!
  updatePicture(
    token: String!
    id: ID!
    units: [ID!]
    models: [ID!]
    description: String!
    date: String!
    tags: [ID!]
  ): Picture!
  deletePicture(token: String!, id: ID!): Picture!
  createDocumentation(
    token: String!
    title: String!
    author: String!
    issueFloat: String!
    publisher: String!
    releaseDate: String!
    type: String!
    url: String!
    model: [ID!]
  ): Documentation!
  updateDocumentation(
    token: String!
    id: ID!
    title: String!
    author: String!
    issueFloat: String!
    publisher: String!
    releaseDate: String!
    type: String!
    url: String!
    model: [ID!]
  ): Documentation!
  deleteDocumentation(token: String!, id: ID!): Documentation!
}

type Manufacturer {
  id: ID!
  name: String!
  shortName: String!
  country: String!
  creationDate: String!
  works: Boolean!
  dateOfLiquidation: String
  heroImage: ID
  moderator: String
  updateDate: Float
  verified: String
}

type LocomotiveModel {
  id: ID!
  factoryType: [String!]
  manufacturer: [ID!]
  intendentUse: String!
  tractionType: String!
  specTable: String!
  series: [String!]
  heroImage: ID
  moderator: String
  updateDate: Float
  verified: String
}

type Owner {
  id: ID!
  name: String!
  isAssociation: Boolean!
  adress: String!
  geopoint: String!
  website: String
  heroImage: ID
  moderator: String
  updateDate: Float
  verified: String
}

type Locomotive {
  id: ID!
  Float: String!
  model: ID!
  owner: ID!
  manufacturer: ID!
  state: String!
  assignments: String
  repairHistory: String
  countryOfOperation: String!
  heroImage: ID
  moderator: String
  updateDate: Float
  verified: String
}

type Tag {
  id: ID!
  name: String!
  moderator: String
  updateDate: Float
  verified: String
}

type Picture {
  id: ID!
  units: [ID!]
  models: [ID!]
  description: String!
  date: String!
  tags: [ID!]
  moderator: String
  updateDate: Float
  verified: String
}

type Documentation {
  id: ID!
  title: String!
  author: String!
  issueFloat: String!
  publisher: String!
  releaseDate: String!
  type: String!
  url: String!
  model: [ID!]
  moderator: String
  updateDate: Float
  verified: String
}

